version: "3.8"

services:
  composer:
    image: composer:2.1.9
    entrypoint: composer
    volumes:
      - .:/IHM

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=symfony
      - POSTGRES_PASSWORD=ChangeMe
      - POSTGRES_DB=IHM
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db
